spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:E:/H2databases/encrypt-system/encrypt-system;AUTO_SERVER=TRUE
    username: geobeans0523
    password: geobeans0523

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 4096MB
      max-request-size: 10240MB
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: true

logging:
  config:
    classpath: log4j2-sprin.yml

server:
  port: 8084
  servlet:
    context-path: /encrypt

app:
  jarRoot: E:/springboot/encrypt